version: "3.8"

services:
  flask_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.flask
    ports:
      - "5000:5000"
    restart: always
    env_file: .env

  discord_bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    ports:
      - "8765:8765"
    restart: always
    env_file: .env